# Use whatever version you are running locally (see node -v)
FROM node:19-bullseye-slim

FROM node:14-alpine

WORKDIR /app

COPY package.json ./

COPY package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
